#!/bin/bash

# *************************************************************************************************
# mediam (Media Maid)
# https://github.com/agileforge/mediam
# *************************************************************************************************
# License: GPL 3
# Author: Pascal Fluck (PFComputing)
# *************************************************************************************************

debug() {
	if [[ $DEBUG ]]; then 
		echo "[DEBUG] $1" 
	fi	
}

verbose() {
	if [[ $VERBOSE ]]; then 
		echo "$1" 
	fi	
}

action() {
	case "$1" in
		copy )
			cp -u -f "$2" "$3"
			verbose "Copy '$2' to '$3'"
			;;
		move )
			mv -f "$2" "$3"
			verbose "Move '$2' to '$3'"
			;;
		link )
			cp -u -f -s "$2" "$3"
			verbose "Link '$2' to '$3'"
			;;
		hlink )
			ln -f "$2" "$3"
			verbose "Hard Link '$2' to '$3'"
	esac
}

typeof() {
	#debug "Search for mime type."
	#local mimetype=$(exiftool -mimetype -m -s -s -s "$f")
	#local mediaType=""
	#debug "mimetype = $mimetype"
	re_image="^.*\.(gif|jpg|jpeg|tiff|png)$"
	re_video="^.*\.(mov|avi|wmv|flv|3gp|mp4|mpg)$"
	if [[ $f =~ $re_image ]]; then
		mediaType="image"
	elif [[ $f =~ $re_video ]]; then
		mediaType="video"
	fi
	__result__=$mediaType
}
